FROM ubuntu:16.04

# Install system packages
RUN apt-get update && apt-get install -y --no-install-recommends \
      bzip2 \
      g++ \
      git \
      graphviz \
      libgl1-mesa-glx \
      libhdf5-dev \
      openmpi-bin \
      wget && \
    rm -rf /var/lib/apt/lists/*

# Install conda
ENV CONDA_DIR /opt/conda
ENV PATH $CONDA_DIR/bin:$PATH

RUN wget --quiet --no-check-certificate https://repo.continuum.io/miniconda/Miniconda3-4.2.12-Linux-x86_64.sh && \
    echo "c59b3dd3cad550ac7596e0d599b91e75d88826db132e4146030ef471bb434e9a *Miniconda3-4.2.12-Linux-x86_64.sh" | sha256sum -c - && \
    /bin/bash /Miniconda3-4.2.12-Linux-x86_64.sh -f -b -p $CONDA_DIR && \
    rm Miniconda3-4.2.12-Linux-x86_64.sh && \
    echo export PATH=$CONDA_DIR/bin:'$PATH' > /etc/profile.d/conda.sh

# Install Python packages and keras
ENV NB_USER keras
ENV NB_UID 1000

RUN useradd -m -s /bin/bash -N -u $NB_UID $NB_USER && \
    chown $NB_USER $CONDA_DIR -R

RUN mkdir -p /src && \
    chown $NB_USER /src

# ADDED
RUN mkdir -p /data && \
    chown $NB_USER /data

USER $NB_USER

ARG python_version=3.6

RUN conda install -y python=${python_version} && \
    pip --default-timeout=1000 install --upgrade pip && \
    pip --default-timeout=1000 install \
      sklearn_pandas \
      tensorflow && \
    conda install \
      bcolz \
      h5py \
      matplotlib \
      mkl \
      nose \
      notebook \
      Pillow \
      pandas \
      pygpu \
      pyyaml \
      scikit-learn \
      six \
      theano && \
    git clone git://github.com/keras-team/keras.git /src && pip install -e /src[tests] && \
    pip --default-timeout=1000 install git+git://github.com/keras-team/keras.git && \
    conda clean -yt

ADD theanorc /home/keras/.theanorc

# ADDED
RUN mkdir /home/keras/.jupyter
ADD jupyter_notebook_config.py /home/keras/.jupyter/jupyter_notebook_config.py

ENV PYTHONPATH='/src/:$PYTHONPATH'

# WORKDIR /src
WORKDIR /data

EXPOSE 8888

# CHANGED from CMD jupyter notebook --port=8888 --ip=0.0.0.0
# We could also define this in jupyter_notebook_config.py above, see tensorflow/tensorflow:latest-gpu example
CMD jupyter notebook --port=8888 --ip=* --no-browser